### ISSUE TITLE
The arm architecture is not supported, is there any plan to support it?

### ISSUE THREAD

**Issue by cr0ssover** [Zxilly/go-size-view#2]

**Comment by Zxilly** [comment]
There is an upcoming refactoring where bloaty will be removed and the arm architecture will be supported after this refactoring, but it will take a while.
You can track the progress in the `pure` branch.

**Comment by cr0ssover** [comment]
Thank you for your response! I'm glad to hear about the upcoming refactoring and the planned support for the arm architecture. I'll keep an eye on the progress in the `pure` branch. Thanks again!
